version: '3.8'

services:
  link-shortener:
    build:
      context: ./services/link-shortener
      dockerfile: Dockerfile
    container_name: notification-link-shortener
    ports:
      - "8001:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - notification-network
    volumes:
      - ./logs/link-shortener:/app/logs

  redis:
    image: redis:7-alpine
    container_name: notification-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - notification-network

volumes:
  redis_data:
    name: notification-redis-data

networks:
  notification-network:
    name: notification-system-network
    driver: bridge