name: Pre-commit checks

on:
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install pre-commit
      run: |
        pip install pre-commit
        pip install hadolint

    - name: Run pre-commit
      run: pre-commit run --all-files