name: Pre-commit checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install hadolint
      run: |
        curl -sSL https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 \
          -o /usr/local/bin/hadolint
        chmod +x /usr/local/bin/hadolint

    - name: Run pre-commit
      run: pre-commit run --all-files